name: Update Documentation
on:
  push

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Request Documentation Update
        run: |
          curl -f -X PUT -H "Authorization:Bearer ${{secrets.DOCS_ADMIN_TOKEN}}" ${{secrets.DOCS_ADMIN_ENDPOINT}}/update > /dev/null
